name: Deploy theme to Let-Me-Out

on:
  push:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: deploy-theme
  cancel-in-progress: true

env:
  THEME_DIR: .

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        if: hashFiles('package.json') != ''
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps (if package.json exists)
        if: hashFiles('package.json') != ''
        run: |
          if [ -f package-lock.json ]; then
            npm ci
          else
            npm install
          fi

      - name: Build assets (if package.json exists)
        if: hashFiles('package.json') != ''
        run: npm run build

      - name: Clean remote theme dir
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ vars.SFTP_HOST }}
          username: ${{ secrets.SFTP_USER }}
          password: ${{ secrets.SFTP_PASS }}
          port: ${{ vars.SFTP_PORT }}
          script: |
            set -e
            REMOTE="${{ vars.SFTP_PATH }}"
            case "$REMOTE" in
              /data/sites/web/*) ;;
              *) echo "Refusing to clean unexpected path: $REMOTE" ; exit 1 ;;
            esac
            mkdir -p "$REMOTE"
            find "$REMOTE" -mindepth 1 -maxdepth 1 -exec rm -rf {} \;

      - name: Upload theme via SCP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ vars.SFTP_HOST }}
          username: ${{ secrets.SFTP_USER }}
          password: ${{ secrets.SFTP_PASS }}
          port: ${{ vars.SFTP_PORT }}
          source: './'
          target: '${{ vars.SFTP_PATH }}'
          overwrite: true
